version: 2
updates:
  # Production dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day-of-month: 1
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "VirtualAgentics"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "production"

  # Development dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day-of-week: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "VirtualAgentics"
    commit-message:
      prefix: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "development"
    groups:
      linting:
        patterns:
          - "black*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
      testing:
        patterns:
          - "pytest*"
          - "coverage*"
          - "bandit*"
          - "safety*"
      documentation:
        patterns:
          - "sphinx*"
          - "sphinx-*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day-of-week: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "VirtualAgentics"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-core:
        patterns:
          - "actions/checkout*"
          - "actions/setup-python*"
          - "actions/upload-artifact*"
          - "actions/download-artifact*"
      actions-pages:
        patterns:
          - "actions/configure-pages*"
          - "actions/upload-pages-artifact*"
          - "actions/deploy-pages*"
      github-security:
        patterns:
          - "github/codeql-action*"
