version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "VirtualAgentics"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      linting:
        patterns:
          - "black*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
      testing:
        patterns:
          - "pytest*"
          - "coverage*"
          - "bandit*"
          - "safety*"
      documentation:
        patterns:
          - "sphinx*"
          - "sphinx-*"
