# Markdown linting configuration for markdownlint-cli2
# https://github.com/DavidAnson/markdownlint

# Enable all rules by default
default: true

# Customize specific rules for project needs
MD013: false  # Line length - disabled (code blocks, URLs can be long)
MD033: false  # Inline HTML - allowed (needed for badges, centered images, etc.)
MD041: false  # First line in file should be top-level heading - disabled (README has badges first)

# Temporarily lenient rules (to be tightened gradually)
MD022: false  # Headings surrounded by blank lines - disabled (2045 violations to fix gradually)
MD031: false  # Fenced code blocks surrounded by blank lines - disabled
MD032: false  # Lists surrounded by blank lines - disabled
MD034: false  # Bare URLs - disabled (use angle brackets for autolinks)
MD040: false  # Fenced code language - disabled
MD036: false  # Emphasis as heading - disabled
MD012: false  # Multiple blank lines - disabled
MD024: false  # Duplicate headings - disabled
