# Markdown linting configuration for markdownlint-cli2
# https://github.com/DavidAnson/markdownlint

# Enable all rules by default
default: true

# Project-specific exceptions (permanent)
MD013: false  # Line length - disabled (code blocks, URLs can be long)
MD033: false  # Inline HTML - allowed (needed for badges, centered images, etc.)
MD041: false  # First line in file should be top-level heading - disabled (README has badges first)
MD024:  # Duplicate headings allowed when in different sections
  siblings_only: true
