# OSV-Scanner Configuration (root applies to manifests in this directory)
# Black < 24.3.0 advisory — we pin 25.9.0, so this is a false positive.

# Try PackageOverrides approach (in addition to IgnoredVulns)
[[PackageOverrides]]
name = "black"
ecosystem = "PyPI"
vulnerability.ignore = true
reason = "Black 25.9.0 includes security fix from March 2024 (commit f000936)"

[[IgnoredVulns]]
id = "PYSEC-2024-48"
reason = "Black pinned to 25.9.0 (>=24.3.0 fixed)."
expires = "2026-03-31"

[[IgnoredVulns]]
id = "GHSA-fj7x-q9j7-g6q6"
reason = "Alias of PYSEC-2024-48; Black pinned to 25.9.0."
expires = "2026-03-31"
