name: Dependency Submission

# This workflow generates and submits an SBOM (Software Bill of Materials) to
# GitHub's dependency graph API. This helps refresh GitHub's understanding of
# our dependencies and their versions.
#
# Purpose: Resolves false positives where vulnerability databases haven't
# recognized that newer package versions include security fixes.
#
# Reference: https://github.com/anchore/sbom-action

on:
  push:
    branches: [main, develop]
    paths:
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/requirements-bootstrap.txt"
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Default permissions: read-only for security
permissions:
  contents: read

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write  # Required to submit SBOM to dependency graph
      id-token: write  # Required for SBOM attestation

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python 3.12
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --require-hashes -r .github/requirements-bootstrap.txt
          pip install -e ".[dev,ml]"

      - name: Generate and Submit SBOM
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
          upload-artifact: true
          upload-release-assets: false
          dependency-snapshot: true  # Submit to GitHub dependency graph
